// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BIblioteka.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    partial class BookStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotekaArtikal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GodinaIzdanja")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookStoreItems", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Film", b =>
                {
                    b.HasBaseType("BibliotekaArtikal");

                    b.Property<string>("Reziser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TrajanjeUMinutama")
                        .HasColumnType("float");

                    b.ToTable("Movies", (string)null);
                });

            modelBuilder.Entity("Knjiga", b =>
                {
                    b.HasBaseType("BibliotekaArtikal");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrojStranica")
                        .HasColumnType("int");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("Film", b =>
                {
                    b.HasOne("BibliotekaArtikal", null)
                        .WithOne()
                        .HasForeignKey("Film", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Knjiga", b =>
                {
                    b.HasOne("BibliotekaArtikal", null)
                        .WithOne()
                        .HasForeignKey("Knjiga", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
