// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Senzori.Migrations
{
    [DbContext(typeof(SenzorsContext))]
    [Migration("20260208184655_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Uredjaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Devices", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Kontroler", b =>
                {
                    b.HasBaseType("Uredjaj");

                    b.Property<int>("BrojKanala")
                        .HasColumnType("int");

                    b.Property<string>("ModelKontrolera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.ToTable("Controllers", (string)null);
                });

            modelBuilder.Entity("Senzor", b =>
                {
                    b.HasBaseType("Uredjaj");

                    b.Property<double>("Vrijednost")
                        .HasColumnType("float");

                    b.Property<string>("grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Senzors", (string)null);
                });

            modelBuilder.Entity("Kontroler", b =>
                {
                    b.HasOne("Uredjaj", null)
                        .WithOne()
                        .HasForeignKey("Kontroler", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Senzor", b =>
                {
                    b.HasOne("Uredjaj", null)
                        .WithOne()
                        .HasForeignKey("Senzor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
