// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(MasterContext))]
    [Migration("20260209130909_InitialMasterDb1")]
    partial class InitialMasterDb1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotekaArtikal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GodinaIzdanja")
                        .HasColumnType("int");

                    b.Property<int>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradId");

                    b.ToTable("Artikli");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CityNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradId");

                    b.ToTable("Nodes");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gradovi");
                });

            modelBuilder.Entity("Uredjaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradId");

                    b.ToTable("Uredjaji");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Film", b =>
                {
                    b.HasBaseType("BibliotekaArtikal");

                    b.Property<string>("Reziser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TrajanjeUMinutama")
                        .HasColumnType("float");

                    b.ToTable("Movies", (string)null);
                });

            modelBuilder.Entity("Knjiga", b =>
                {
                    b.HasBaseType("BibliotekaArtikal");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrojStranica")
                        .HasColumnType("int");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("CrossRoad", b =>
                {
                    b.HasBaseType("CityNode");

                    b.Property<string>("CrossName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TrafficJamPercantage")
                        .HasColumnType("float");

                    b.ToTable("CrossRoads", (string)null);
                });

            modelBuilder.Entity("ParkingLot", b =>
                {
                    b.HasBaseType("CityNode");

                    b.Property<int>("AvailableParkingSpots")
                        .HasColumnType("int");

                    b.Property<string>("ParkingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalParkingSpots")
                        .HasColumnType("int");

                    b.ToTable("ParkingLots", (string)null);
                });

            modelBuilder.Entity("Kontroler", b =>
                {
                    b.HasBaseType("Uredjaj");

                    b.Property<int>("BrojKanala")
                        .HasColumnType("int");

                    b.Property<string>("ModelKontrolera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.ToTable("Controllers", (string)null);
                });

            modelBuilder.Entity("Senzor", b =>
                {
                    b.HasBaseType("Uredjaj");

                    b.Property<double>("Vrijednost")
                        .HasColumnType("float");

                    b.ToTable("Senzors", (string)null);
                });

            modelBuilder.Entity("BibliotekaArtikal", b =>
                {
                    b.HasOne("Domain.Models.Grad", "Grad")
                        .WithMany("BookStoreInventory")
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("CityNode", b =>
                {
                    b.HasOne("Domain.Models.Grad", "Grad")
                        .WithMany("CityNodes")
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("Uredjaj", b =>
                {
                    b.HasOne("Domain.Models.Grad", "Grad")
                        .WithMany("Devices")
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("Film", b =>
                {
                    b.HasOne("BibliotekaArtikal", null)
                        .WithOne()
                        .HasForeignKey("Film", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Knjiga", b =>
                {
                    b.HasOne("BibliotekaArtikal", null)
                        .WithOne()
                        .HasForeignKey("Knjiga", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CrossRoad", b =>
                {
                    b.HasOne("CityNode", null)
                        .WithOne()
                        .HasForeignKey("CrossRoad", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParkingLot", b =>
                {
                    b.HasOne("CityNode", null)
                        .WithOne()
                        .HasForeignKey("ParkingLot", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kontroler", b =>
                {
                    b.HasOne("Uredjaj", null)
                        .WithOne()
                        .HasForeignKey("Kontroler", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Senzor", b =>
                {
                    b.HasOne("Uredjaj", null)
                        .WithOne()
                        .HasForeignKey("Senzor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Grad", b =>
                {
                    b.Navigation("BookStoreInventory");

                    b.Navigation("CityNodes");

                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
