services:
  # Ovo je tvoj novi SQL Server koji radi na Linuxu
  smartcity.db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Kazazovic3004!

    ports:
      - "1433:1433"

  # Tvoj API
  api_ui:
    image: ${DOCKER_REGISTRY-}apiui
    build:
      context: .
      dockerfile: API_UI/Dockerfile
    depends_on:
      - smartcity.db
    environment:
     - ConnectionStrings__DefaultConnection=Server=smartcity.db;Database=SmartCityDb;User Id=sa;Password=Kazazovic3004!;TrustServerCertificate=True;