// <auto-generated />
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(MasterContext))]
    [Migration("20260213113235_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Client", b =>
                {
                    b.HasBaseType("Domain.Models.Person");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Name = "Atlantbh",
                            CompanyName = "Atlantbh d.o.o.",
                            Email = "info@atlantbh.com"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Microsoft",
                            CompanyName = "Microsoft Corporation",
                            Email = "support@microsoft.com"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Google",
                            CompanyName = "Google LLC"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mistral",
                            CompanyName = "Mistral Technologies",
                            Email = "contact@mistral.ba"
                        });
                });

            modelBuilder.Entity("Domain.Models.Worker", b =>
                {
                    b.HasBaseType("Domain.Models.Person");

                    b.Property<double?>("ExperienceInYears")
                        .HasColumnType("float");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Workers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dženan Kazazović",
                            ExperienceInYears = 2.5,
                            Position = "Backend Developer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Amar Delić",
                            ExperienceInYears = 3.0,
                            Position = "Frontend Developer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lejla Hodžić",
                            ExperienceInYears = 1.2,
                            Position = "DevOps Engineer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sara Ibrahimović",
                            Position = "Junior QA"
                        });
                });

            modelBuilder.Entity("Domain.Models.Client", b =>
                {
                    b.HasOne("Domain.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.Client", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Worker", b =>
                {
                    b.HasOne("Domain.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.Worker", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
