// <auto-generated />
using BookTrackerFirstApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookTrackerFirstApi.Migrations
{
    [DbContext(typeof(MasterContext))]
    partial class MasterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookTrackerFirstApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Ivo Andrić",
                            Description = "Istorijski roman o mostu.",
                            IsRead = true,
                            Name = "Na Drini ćuprija"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Meša Selimović",
                            Description = "Psihološka drama o pojedincu i sistemu.",
                            IsRead = false,
                            Name = "Tvrđava"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Robert C. Martin",
                            Description = "Biblija za developere.",
                            IsRead = true,
                            Name = "Clean Code"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Andrew Hunt",
                            Description = "Savjeti za moderan razvoj softvera.",
                            IsRead = false,
                            Name = "The Pragmatic Programmer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
