// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SmartCity.Migrations
{
    [DbContext(typeof(CityContext))]
    partial class CityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CityNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CityNodes", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CrossRoad", b =>
                {
                    b.HasBaseType("CityNode");

                    b.Property<string>("CrossName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TrafficJamPercantage")
                        .HasColumnType("float");

                    b.ToTable("CrossRoads", (string)null);
                });

            modelBuilder.Entity("ParkingLot", b =>
                {
                    b.HasBaseType("CityNode");

                    b.Property<int>("AvailableParkingSpots")
                        .HasColumnType("int");

                    b.Property<string>("ParkingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalParkingSpots")
                        .HasColumnType("int");

                    b.ToTable("ParkingLots", (string)null);
                });

            modelBuilder.Entity("CrossRoad", b =>
                {
                    b.HasOne("CityNode", null)
                        .WithOne()
                        .HasForeignKey("CrossRoad", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParkingLot", b =>
                {
                    b.HasOne("CityNode", null)
                        .WithOne()
                        .HasForeignKey("ParkingLot", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
